name = "Localhost App"
client_id = "d3ed6a72ae1417ffaafb3a11b09c063a"

application_url = "https://localhost:3000/"
embedded = true
handle = "localhost"

[access_scopes]
scopes = "read_products"

[access.admin]
direct_api_mode = "online"

[auth]
redirect_urls = [
  "https://localhost:3000/api/auth/callback",
  "https://localhost:3000/api/auth/oauth/callback",
]

[customer_authentication]
redirect_uris = [
  "https://localhost:3000/api/customer/auth/callback"
]
javascript_origins = [
  "https://localhost:3000/"
]
logout_urls = [
  "https://localhost:3000/api/customer/logout"
]


[build]
automatically_update_urls_on_dev = false